// Code generated by mockery v2.25.0. DO NOT EDIT.

package mocks

import (
	context "context"
	dto "course/internal/service/dto"

	mock "github.com/stretchr/testify/mock"

	model "course/internal/model"
)

// FieldStorage is an autogenerated mock type for the FieldStorage type
type FieldStorage struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, request
func (_m *FieldStorage) Create(ctx context.Context, request *dto.CreateCardFieldRequest) error {
	ret := _m.Called(ctx, request)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *dto.CreateCardFieldRequest) error); ok {
		r0 = rf(ctx, request)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: ctx, request
func (_m *FieldStorage) Delete(ctx context.Context, request *dto.DeleteCardFieldRequest) error {
	ret := _m.Called(ctx, request)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *dto.DeleteCardFieldRequest) error); ok {
		r0 = rf(ctx, request)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Get provides a mock function with given fields: ctx, request
func (_m *FieldStorage) Get(ctx context.Context, request *dto.GetCardFieldRequest) (*model.Field, error) {
	ret := _m.Called(ctx, request)

	var r0 *model.Field
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *dto.GetCardFieldRequest) (*model.Field, error)); ok {
		return rf(ctx, request)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *dto.GetCardFieldRequest) *model.Field); ok {
		r0 = rf(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Field)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *dto.GetCardFieldRequest) error); ok {
		r1 = rf(ctx, request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListCardFields provides a mock function with given fields: ctx, request
func (_m *FieldStorage) ListCardFields(ctx context.Context, request *dto.ListCardFieldsRequest) ([]*model.Field, error) {
	ret := _m.Called(ctx, request)

	var r0 []*model.Field
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *dto.ListCardFieldsRequest) ([]*model.Field, error)); ok {
		return rf(ctx, request)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *dto.ListCardFieldsRequest) []*model.Field); ok {
		r0 = rf(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.Field)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *dto.ListCardFieldsRequest) error); ok {
		r1 = rf(ctx, request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewFieldStorage interface {
	mock.TestingT
	Cleanup(func())
}

// NewFieldStorage creates a new instance of FieldStorage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewFieldStorage(t mockConstructorTestingTNewFieldStorage) *FieldStorage {
	mock := &FieldStorage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
