// Code generated by mockery v2.25.0. DO NOT EDIT.

package mocks

import (
	context "context"
	dto "course/internal/service/dto"

	mock "github.com/stretchr/testify/mock"

	model "course/internal/model"
)

// InfoCardStorage is an autogenerated mock type for the InfoCardStorage type
type InfoCardStorage struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, request
func (_m *InfoCardStorage) Create(ctx context.Context, request *dto.CreateInfoCardRequest) error {
	ret := _m.Called(ctx, request)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *dto.CreateInfoCardRequest) error); ok {
		r0 = rf(ctx, request)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: ctx, request
func (_m *InfoCardStorage) Delete(ctx context.Context, request *dto.DeleteInfoCardRequest) error {
	ret := _m.Called(ctx, request)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *dto.DeleteInfoCardRequest) error); ok {
		r0 = rf(ctx, request)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetByID provides a mock function with given fields: ctx, request
func (_m *InfoCardStorage) GetByID(ctx context.Context, request *dto.GetInfoCardRequest) (*model.InfoCard, error) {
	ret := _m.Called(ctx, request)

	var r0 *model.InfoCard
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *dto.GetInfoCardRequest) (*model.InfoCard, error)); ok {
		return rf(ctx, request)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *dto.GetInfoCardRequest) *model.InfoCard); ok {
		r0 = rf(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.InfoCard)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *dto.GetInfoCardRequest) error); ok {
		r1 = rf(ctx, request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// List provides a mock function with given fields: ctx, request
func (_m *InfoCardStorage) List(ctx context.Context, request *dto.ListInfoCardsRequest) ([]*model.InfoCard, error) {
	ret := _m.Called(ctx, request)

	var r0 []*model.InfoCard
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *dto.ListInfoCardsRequest) ([]*model.InfoCard, error)); ok {
		return rf(ctx, request)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *dto.ListInfoCardsRequest) []*model.InfoCard); ok {
		r0 = rf(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.InfoCard)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *dto.ListInfoCardsRequest) error); ok {
		r1 = rf(ctx, request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Validate provides a mock function with given fields: ctx, request
func (_m *InfoCardStorage) Validate(ctx context.Context, request *dto.ValidateInfoCardRequest) error {
	ret := _m.Called(ctx, request)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *dto.ValidateInfoCardRequest) error); ok {
		r0 = rf(ctx, request)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewInfoCardStorage interface {
	mock.TestingT
	Cleanup(func())
}

// NewInfoCardStorage creates a new instance of InfoCardStorage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewInfoCardStorage(t mockConstructorTestingTNewInfoCardStorage) *InfoCardStorage {
	mock := &InfoCardStorage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
