// Code generated by mockery v2.42.1. DO NOT EDIT.

package mocks

import (
	context "context"
	dto "course/internal/service/dto"

	mock "github.com/stretchr/testify/mock"

	model "course/internal/model"
)

// CompanyStorage is an autogenerated mock type for the CompanyStorage type
type CompanyStorage struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, request
func (_m *CompanyStorage) Create(ctx context.Context, request *dto.CreateCompanyRequest) (*model.Company, error) {
	ret := _m.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *model.Company
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *dto.CreateCompanyRequest) (*model.Company, error)); ok {
		return rf(ctx, request)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *dto.CreateCompanyRequest) *model.Company); ok {
		r0 = rf(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Company)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *dto.CreateCompanyRequest) error); ok {
		r1 = rf(ctx, request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: ctx, request
func (_m *CompanyStorage) Delete(ctx context.Context, request *dto.DeleteCompanyRequest) error {
	ret := _m.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *dto.DeleteCompanyRequest) error); ok {
		r0 = rf(ctx, request)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetByID provides a mock function with given fields: ctx, request
func (_m *CompanyStorage) GetByID(ctx context.Context, request *dto.GetCompanyRequest) (*model.Company, error) {
	ret := _m.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *model.Company
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *dto.GetCompanyRequest) (*model.Company, error)); ok {
		return rf(ctx, request)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *dto.GetCompanyRequest) *model.Company); ok {
		r0 = rf(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Company)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *dto.GetCompanyRequest) error); ok {
		r1 = rf(ctx, request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewCompanyStorage creates a new instance of CompanyStorage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCompanyStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *CompanyStorage {
	mock := &CompanyStorage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
