// Code generated by mockery v2.42.1. DO NOT EDIT.

package mocks

import (
	context "context"
	dto "course/internal/service/dto"

	mock "github.com/stretchr/testify/mock"

	model "course/internal/model"
)

// EmployeeStorage is an autogenerated mock type for the EmployeeStorage type
type EmployeeStorage struct {
	mock.Mock
}

// Delete provides a mock function with given fields: ctx, request
func (_m *EmployeeStorage) Delete(ctx context.Context, request *dto.DeleteEmployeeRequest) error {
	ret := _m.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *dto.DeleteEmployeeRequest) error); ok {
		r0 = rf(ctx, request)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetByInfoCardID provides a mock function with given fields: ctx, request
func (_m *EmployeeStorage) GetByInfoCardID(ctx context.Context, request *dto.GetEmployeeByInfoCardIDRequest) (*model.Employee, error) {
	ret := _m.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for GetByInfoCardID")
	}

	var r0 *model.Employee
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *dto.GetEmployeeByInfoCardIDRequest) (*model.Employee, error)); ok {
		return rf(ctx, request)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *dto.GetEmployeeByInfoCardIDRequest) *model.Employee); ok {
		r0 = rf(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Employee)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *dto.GetEmployeeByInfoCardIDRequest) error); ok {
		r1 = rf(ctx, request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByPhone provides a mock function with given fields: ctx, request
func (_m *EmployeeStorage) GetByPhone(ctx context.Context, request *dto.GetEmployeeRequest) (*model.Employee, error) {
	ret := _m.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for GetByPhone")
	}

	var r0 *model.Employee
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *dto.GetEmployeeRequest) (*model.Employee, error)); ok {
		return rf(ctx, request)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *dto.GetEmployeeRequest) *model.Employee); ok {
		r0 = rf(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Employee)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *dto.GetEmployeeRequest) error); ok {
		r1 = rf(ctx, request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Register provides a mock function with given fields: ctx, request
func (_m *EmployeeStorage) Register(ctx context.Context, request *dto.RegisterEmployeeRequest) (*model.Employee, error) {
	ret := _m.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for Register")
	}

	var r0 *model.Employee
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *dto.RegisterEmployeeRequest) (*model.Employee, error)); ok {
		return rf(ctx, request)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *dto.RegisterEmployeeRequest) *model.Employee); ok {
		r0 = rf(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Employee)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *dto.RegisterEmployeeRequest) error); ok {
		r1 = rf(ctx, request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateRefreshToken provides a mock function with given fields: ctx, request
func (_m *EmployeeStorage) UpdateRefreshToken(ctx context.Context, request *dto.UpdateToken) error {
	ret := _m.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for UpdateRefreshToken")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *dto.UpdateToken) error); ok {
		r0 = rf(ctx, request)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewEmployeeStorage creates a new instance of EmployeeStorage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewEmployeeStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *EmployeeStorage {
	mock := &EmployeeStorage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
