// Code generated by mockery v2.25.0. DO NOT EDIT.

package storage

import (
	context "context"
	dto "course/internal/service/dto"

	mock "github.com/stretchr/testify/mock"

	model "course/internal/model"
)

// MockCompanyStorage is an autogenerated mock type for the CompanyStorage type
type MockCompanyStorage struct {
	mock.Mock
}

// GetByID provides a mock function with given fields: ctx, request
func (_m *MockCompanyStorage) GetByID(ctx context.Context, request *dto.GetCompanyRequest) (*model.Company, error) {
	ret := _m.Called(ctx, request)

	var r0 *model.Company
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *dto.GetCompanyRequest) (*model.Company, error)); ok {
		return rf(ctx, request)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *dto.GetCompanyRequest) *model.Company); ok {
		r0 = rf(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Company)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *dto.GetCompanyRequest) error); ok {
		r1 = rf(ctx, request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewMockCompanyStorage interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockCompanyStorage creates a new instance of MockCompanyStorage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockCompanyStorage(t mockConstructorTestingTNewMockCompanyStorage) *MockCompanyStorage {
	mock := &MockCompanyStorage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
